### ISSUE TITLE
work done?

### ISSUE THREAD

**Issue by amir1376irani** [FONQRI/FLogProject#1]
Hi Mr.Behnam. Glad to see the library i used in 2 mid-size-project was your work.
By the way don't you wanna continue developing it?

**Comment by FONQRI** [comment]
> Hi Mr.Behnam. Glad to see the library i used in 2 mid-size-project was your work.
> By the way don't you wanna continue developing it?

If you're using it in a mid-size project it's OK but if you need more features i suggest [boost.log](https://www.boost.org/doc/libs/1_72_0/libs/log/doc/html/index.html).
